---
- name: Disable swap memory
  hosts: kubernetes
  become: true
  tasks:
    - block:
      - name: Disabilita la memoria di swap
        command: swapoff -a

      - name: Backup del file fstab
        copy:
          src: /etc/fstab
          dest: /etc/fstab.bak
          remote_src: true

      - name: Rimuove le voci di swap da /etc/fstab
        lineinfile:
          path: /etc/fstab
          regexp: '.*swap.*'
          state: absent
